[FILTER]
    Name   rewrite_tag
    Match  app.logs
    Rule   levelname INFO info.logs false

[FILTER]
    Name   rewrite_tag
    Match  app.logs
    Rule   levelname ERROR error.logs false

[FILTER]
    Name   rewrite_tag
    Match  app.logs
    Rule   levelname ^$ dead.logs false

