[OUTPUT]
    Name   stdout
    Match  app.logs

[OUTPUT]
    Name            es
    Match           info.logs,error.logs,dead.logs

    Host            localhost
    Port            9200
    Index           soc-logs
    Logstash_Format On
    Replace_Dots    On

    Suppress_Type_Name On
    TLS             Off
    Retry_Limit     False

