[OUTPUT]
    Name stdout
    Match info.logs

[OUTPUT]
    Name stdout
    Match error.logs

[OUTPUT]
    Name stdout
    Match dead.logs

[OUTPUT]
    Name            es
    Match           *
    Host            localhost
    Port            9200
    Index           soc-logs
    Type            _doc
    Logstash_Format On
    Retry_Limit     False

