[OUTPUT]
    Name   stdout
    Match  soc.logs

[OUTPUT]
    Name            es
    Match           soc.logs

    Host            localhost
    Port            9200
    Index           soc-logs
    Logstash_Format On
    Logstash_Prefix soc-logs
    Replace_Dots    On

    Suppress_Type_Name On
    TLS             Off
    Retry_Limit     False

